api_login_check:
  path: /api/login
  methods: [POST]
  controller: App\Controller\Security\SecurityController::loginCheck

api_forgot_check:
  path: /api/forgot
  methods: [POST]
  controller: App\Controller\Security\SecurityController::forgotCheck

api_logout_check:
  path: /api/logout
  methods: [POST]
  controller: App\Controller\Security\SecurityController::logoutCheck


